acting_batch_size: 32
acting_round: 40
activity_cutoff: 6.0
activity_lower_bound: 5.5
activity_ratio: 1.5
activity_upper_bound: 8.5
batch_size: 256
center_x: null
center_y: null
center_z: null
clip_epsilon: 0.1
design_log: ./GBA_design/design.log
entropy_coeff: 0.001
feature_dims: 64
gamma: 0.99
initial_param: ./expert_training/expert_iter-1000000
learning_rate: 0.0001
ligand_sdf: ./GBA_design/crystal_ligand.sdf
max_action: 50
njobs: 8
out_sdf: ./GBA_design/desired.sdf
protein_pdb: ./GBA_design/prepared_receptor.pdb
qed_cutoff: 0.6
qed_lower_bound: 0.2
qed_ratio: 1.0
qed_upper_bound: 0.8
sascore_cutoff: 2.5
sascore_lower_bound: 2.0
sascore_ratio: 1.0
sascore_upper_bound: 3.5
start_mol: null
time_limit: 3.0
tmp_states_dir: ./GBA_design/tmp_states_dir/
training_epoch: 1
training_log: ./GBA_design/training.log
update_iters: 3
work_dir: ./GBA_design/
